### ISSUE TITLE
package-git's stringify dependency cannot be resolved

### ISSUE THREAD

**Issue by sr229** [ClaraIO/codebox#4]
needs investigation why

```prolog

[error][packages] { Error: Cannot find module 'stringify' from '/home/user/.codebox/packages/git'
    at /projects/codebox/node_modules/resolve/lib/async.js:48:31
    at processDirs (/projects/codebox/node_modules/resolve/lib/async.js:182:39)
    at ondir (/projects/codebox/node_modules/resolve/lib/async.js:197:13)
    at load (/projects/codebox/node_modules/resolve/lib/async.js:80:43)
    at onex (/projects/codebox/node_modules/resolve/lib/async.js:105:17)
    at /projects/codebox/node_modules/resolve/lib/async.js:26:73
    at FSReqWrap.oncomplete (fs.js:114:15)
  code: 'MODULE_NOT_FOUND',
```

**Comment by sr229** [comment]
fixed from commit 8b3a7cac24c71ce8f1f6a5f85f77f5a822235f78
